### ISSUE TITLE
wrong declaration in README.md

### ISSUE THREAD

**Issue by JH1616** [SaMuELToLoKo/homebridge-advanced-thermostat#1]
First of all thank You for the great implementation of the homebridge thermostat.

I only have had one problem, cause you write in the README.md 
Set target State
```
GET /targetTemperature/{FLOAT_VALUE}    // Target Temperature
OK (200)
```

but you use in your code:
```
return request.post({
					url: this.apiAdress + '/targetTemperature/' + value,
					auth: {
						user: this.username,
						pass: this.password
				}
```

so I think it has to be:
```
POST /targetTemperature/{FLOAT_VALUE}    // Target Temperature
OK (200)
```

**Comment by JH1616** [comment]
also: 
```
GET /setTargetState/{INT_VALUE}         // 0 OFF 1 HEAT 2 COOL 3 AUTO
OK (200)
```

but additionally you use Jason to unpack the body:

```
if (!err && response.statusCode === 200) {
					this.log(JSON.parse(body));
					this.log('response succes');
					return callback(null);
```

so if you don't send `{}` back your homebridge crash.

**Comment by SaMuELToLoKo** [comment]
Thanks for your comments,this is really helpful. Let me some time to check it out. I'm still working in it so I'm sure there is more problems to sort it out but I really appreciate it
