### ISSUE TITLE
Adding a thermometer

### ISSUE THREAD

**Issue by cheitzig** [SaMuELToLoKo/homebridge-advanced-thermostat#10]
Hi,

Wondering if I might elicit your help in resolving an issue I’m having. I tried to extend @jmbwell version of your code to allow for a Temperature Sensor. See: https://github.com/cheitzig/homebridge-infinitive-thermostat Note: I would’ve also asked @jmbwell too, but I can’t figure out how to contact him on his GitHub because Issues seem to be disabled.

The code I added includes:
- A new “getter” called getCurrentOutsideTemperature
- A new service called TemperatureService

If I just hard-set the outdoor temperature (line 39), and update the TemperatureService’s CurrentTemperature characteristic to that value (lines 706-710), the Temperature Sensor shows up fine. Also, if I call the same “getter” that is used for the internal temperature (line 708, currently commented out), things work fine (or rather, then outside temperature is listed as the inside temperature, which at least appears to work).

If I write my own “getter” though, getCurrentOutdoorTemperature, and call it on line 709, the TemperatureSensor gives an error that says "This accessory isn't responding". getCurrentOutdoorTemperature is almost identical to the existing getCurrentTemperature function with the exception of getting the outside vs. the inside temperature from my furnace API (infinitive, another GitHub project).

Any insights?

**Comment by jmbwell** [comment]
Hi! I enabled issues, if you want to reopen this over there. My fork bears only a skeletal similarity to the upstream at this point, so I don’t know whether your issue applies here or not. I’ll take a closer look. Do you get an error or a dump when Homebridge crashes?

**Comment by cheitzig** [comment]
Thanks! I reposted on your page, @jmbwell.
@SaMuELToLoKo, I'll close this version of the issue because I re-opened on @jmbwell's page (https://github.com/jmbwell/homebridge-infinitive-thermostat/issues/1), but if you have any thoughts or insights, I'm all ears!
