### ISSUE TITLE
Tutorial 

### ISSUE THREAD

**Issue by elkorleone** [SaMuELToLoKo/homebridge-advanced-thermostat#2]
Hi!
I would like to make a project with your files but i’m a newbie. Pluging for homebridge is easy for me, but i dont know how to configure an esp8266 (i have sonoffs, wemos mini D1 and nodemcus)
Now I use a hacked sonoff with DHT22 and espeasy but using rules in EVE app and cannot set an especific temperature in HomeKit 
Do you have a tutorial?

Awesome work!

**Comment by SaMuELToLoKo** [comment]
Hello, first of all thanks to try my project, I really appreciate you like it!

The ESP8266 I'm using with is ESP-12E but you can get this project working with your NodeMCU easily.

I don't have any Tutorial wrote already but I can help in whatever you need.

For this project you'll need two ESP8266 (The one you like more).

One of them is to get the temperature. This one will send the current temperature and humidity to the central (the other ESP8266, this is the one with is gonna switch on/off your Central Heating based in the Current Temperature and your set up ).

The second one is in charge to manage the central heating.

You can check the code to know what information you have to change to get the system working.

Let me know what problem are you having and I'll help you out in everything I can.

Also I want to apologize if my English it isn't correct.

Have a nice day and hope you can get it working soon.

Cheers!

**Comment by elkorleone** [comment]
do you speak spanish??

**Comment by SaMuELToLoKo** [comment]
Well, I’m Spanish lol

**Comment by elkorleone** [comment]
Yo también! Como podemos ponernos en contacto?

Enviado desde mi iPad

**Comment by SaMuELToLoKo** [comment]
Este es mi correo

samuelgtmdo@hotmail.com

Podemos hablar por Skype si lo prefieres
