### ISSUE TITLE
Carrier Cor?

### ISSUE THREAD

**Issue by thatvirtualboy** [SaMuELToLoKo/homebridge-advanced-thermostat#3]
Thanks for this plugin! Can it work with the Carrier Cor TP-WEM01? That specific model isn't homekit enabled by default, though its predecessor TP-WEM01-A _is_ homekit enabled by default. 

I don't know how to find the API Address, but I am able to add 'apps' in the Cor's homepage via an authorization code..

**Comment by SaMuELToLoKo** [comment]
Hello, check the oficial website, I think the company has just released HomeKit compatibility. Greetings
