### ISSUE TITLE
Errors with Carrier API??

### ISSUE THREAD

**Issue by BlindFancyJack** [SaMuELToLoKo/homebridge-advanced-thermostat#6]
Hi I am hoping you can help me out here... I have a Carrier MyInfinity system.  It lists the myinfinity server as www.api.ing.carrier.com and port 80  I enter this into the config but get errors when I open homekit, the thermostat changes to no response.  I do not see anywhere to enter the username or password and am looking to fix this error in connecting to the api.  I am new to this and need help please.

Thanks!!!

**Comment by SaMuELToLoKo** [comment]
I’m so sorry I’ve been disconnected for so long. I’m hoping you have this issue fixed by this time, if that’s not the case, can you please be more specific, maybe this plugin is not compatible with your actual system. Thank you and sorry to text you back so late.
